---
language: php
php:
 - 5.4
before_script:
 - pear config-set preferred_state beta
 - printf "\n" | pecl install imagick
 - composer install
 - cp tests/settings.inc.travis settings.inc
 - mysql -e 'create database test;'
 - cd tools; php dbimport.php ../sql/tables.sql
script:
 - cd tests; phpunit .