---
language: php
php:
 - 5.4
before_script:
 - pear config-set preferred_state beta
 - printf "\n" | pecl install imagick
 - composer install
 - cp settings.inc.default settings.inc
script:
 - cd tests; phpunit .