---
language: php
php:
 - 5.4
before_script:
 - pear config-set preferred_state beta
 - printf "\n" | pecl install imagick
 - composer install --prefer-source
 - cp tests/settings.inc.travis settings.inc
 - mysql -e 'create database jvo_test;'
 - cd tools
 - php dbimport.php ../sql/tables.sql
 - php dbimport.php ../tests/travis.sql
 - cd ..
script:
 - cd tests; phpunit .