---
language: php
php:
 - 5.4
 - 5.5
before_script:
 - pear config-set preferred_state beta
 - printf "\n" | pecl install imagick
 - composer self-update
 - composer install --prefer-source
 - cp tests/travis/settings.inc.travis settings.inc
 - mysql -e 'create database jvo_test;'
 - cd tools
 - php dbimport.php ../sql/tables.sql
 - php dbimport.php ../tests/travis/travis.sql