#! /bin/bash

BRANCH=$1

if [ "$1" == "" ]; then
 BRANCH="stable"
fi

git checkout $BRANCH
git pull
/usr/local/bin/composer update --prefer-source
/usr/local/bin/composer install --working-dir .
/usr/local/bin/bower install
